# Generated by Django 4.1.3 on 2024-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='buyer',
            name='addressline2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='buyer',
            name='addressline3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
