# Generated by Django 4.1.3 on 2024-02-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_subcategory_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic4',
            new_name='profile_picture',
        ),
    ]
